# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_merge_dgCMatrices_rcpp <- function(mat_list, mat_colnames, all_colnames) {
    .Call('_Matrix_Layered_col_merge_dgCMatrices_rcpp', PACKAGE = 'Matrix.Layered', mat_list, mat_colnames, all_colnames)
}

